version: '3.7'
services:
  postgres_db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes: 
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_DB: hello
      # POSTGRES_PASSWORD: 
